import NavbarContainer from "./components/navbarContainer.js";
import LandingPage from "./components/landingPage.js";
import MusicPlayerContainer from "./components/musicPlayerContainer.js";
import ItemList from "./components/itemListContainer.js";
import data from "./components/fakeData.js";
import UploadForm from "./components/uploadForm.js";
import LoginForm from "./components/loginForm.js";
import RegisterForm from "./components/registerForm.js";
import UserMenu from "./components/userMenu.js";
